ARTIFICIAL NEURAL NETWORK 
(Churn_Modeling)

In [4]:
#Import the library
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
tf.__version__

'2.3.0'

In [18]:
# Data Preprocessing
df = pd.read_csv('Churn_Modelling.csv')
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [21]:
# encode categorical variable for gender 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [22]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [27]:
# encode categorical variable for country
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [28]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [29]:
#train and test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [30]:
#feature scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Building the ANN**

In [31]:
# Initializing the ANN
ann = tf.keras.models.Sequential()

In [34]:
#add the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [39]:
#add the second hidden layer 
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [40]:
#add the outpput layer
ann.add(tf.keras.layers.Dense(units= 1,activation='sigmoid'))

**Traninng the ANN**

In [45]:
#compile the ann
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy', metrics = 'accuracy')
#since we are dealing with only 1 and 0 thats why we are using binary_crossentropy
#if we are dealing with categorical than loss function will be categorical_crossentropy 
# and activation is softmax

In [48]:
# Trainning the ANN on the trainning set 
ann.fit(X_train,y_train,batch_size = 32 ,epochs = 100 )

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3811 - accuracy: 0.8353
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3793 - accuracy: 0.8360
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3779 - accuracy: 0.8411
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3764 - accuracy: 0.8407
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3748 - accuracy: 0.8415
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3736 - accuracy: 0.8443
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3727 - accuracy: 0.8418
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3714 - accuracy: 0.8444
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3703 - accuracy: 0.8469
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3687 - accura

Predictions

In [55]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[False]]


In [57]:
#predict the Test set result
y_pred = ann.predict(X_test)
y_pred = (y_pred >0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1) 
                     , y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [59]:
#make the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1586    9]
 [ 347   58]]


In [63]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.822